version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
          - 'angular-eslint'
      nx:
        patterns:
          - '@nx/*'
          - 'nx'
      testing:
        patterns:
          - 'jest*'
          - '@types/jest'
          - 'ts-jest'
          - '@playwright/test'
          - 'eslint-plugin-playwright'
      lint-format:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
          - 'prettier'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - dependencies
      - ci
