// Typed token values (generated by `npm run tokens:build`). Prefer CSS vars in styles;
// use these constants only where CSS custom properties are unavailable (e.g. canvas, charts).
export * from './generated/tokens';

/** Attribute + values used to switch theme on <html>. */
export const THEME_ATTRIBUTE = 'data-theme';
export type Theme = 'light' | 'dark';
